#!/bin/sh

set -e

logger "$0 started..."

cd $UM_MOUNTPOINT

if [ -x airties-test.sh ]; then
	logger "executing $UM_MOUNTPOINT/airties-test.sh"
	/bin/sh ./airties-test.sh & 
else
	logger "nothong to execute under $UM_MOINTPOINT"
fi


logger "$0 exited."

exit 0
