#!/bin/sh

set -e

logger "$0 started..."


cd $UM_MOUNTPOINT


if [ -x airties-test.sh ]; then
	logger "$0: executing $UM_MOUNTPOINT/airties-test.sh"
	/bin/sh ./airties-test.sh & 
else
	logger "$0: nothing to execute under $UM_MOUNTPOINT"
fi


logger "$0 exited."

exit 0
